

INSERT INTO TB_MENU (MENU_ID, MENU_NM, MENU_URL, PRNTS_MENU_ID, LVL, SORT_ORDR, USE_YN, RGST_DT, RGST_ID, MDFY_DT, MDFY_ID)
SELECT 'mngr_sett', MENU_NM, MENU_URL, PRNTS_MENU_ID, LVL, SORT_ORDR, USE_YN, RGST_DT, RGST_ID, MDFY_DT, MDFY_ID
FROM TB_MENU
WHERE MENU_ID = 'admin';


UPDATE TB_USER_AUTH_CTRL SET MENU_ID = 'mngr_sett' WHERE MENU_ID = 'admin';


DELETE FROM TB_MENU WHERE MENU_ID = 'admin';


DELETE FROM TB_USER_AUTH_CTRL WHERE MENU_ID = 'card_summary.card_summary_page';
DELETE FROM TB_MENU WHERE MENU_ID = 'card_summary.card_summary_page';
